version: 2
jobs:
  build:
    docker:
      - image: node:8.2.1
    working_directory: ~/app
    steps:
      - checkout
      - run: yarn
      - run: "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn ci
